# Generated by Django 3.1.5 on 2021-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='password2',
            field=models.CharField(default='Password validation', max_length=50),
        ),
    ]
