# Generated by Django 3.1.5 on 2021-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userauth_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='password2',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
