# Generated by Django 3.1.5 on 2021-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('nutriscore', models.CharField(max_length=1)),
                ('image', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('products', models.ManyToManyField(db_table='assoc_cat_ali', related_name='categories', to='products.Product')),
            ],
        ),
    ]
