# Generated by Django 3.1.6 on 2021-02-15 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('nutriscore', models.CharField(max_length=1)),
                ('image', models.URLField()),
                ('small_image', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('products', models.ManyToManyField(db_table='assoc_cat_ali', related_name='categories', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ali_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ali_source', to='products.product')),
                ('ali_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ali_sub', to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ali_source', 'ali_sub')},
            },
        ),
    ]
