# Generated by Django 3.1.6 on 2021-02-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ali_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ali_source', to='products.product')),
                ('ali_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ali_sub', to='products.product')),
            ],
            options={
                'unique_together': {('ali_source', 'ali_sub')},
            },
        ),
    ]
